# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 2.7

env:
  - TOXENV=py27
  - TOXENV=pypy

before_install:
  - sudo docker pull pynedist/pyne-ubuntu

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# copy the git repo being tested into the docker instance
   - sudo docker run pynedist/pyne-ubuntu /bin/sh -c "cd /root/opt/"
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker cp ../pyne $commit_id:/root/opt/pyne
#   - sudo docker run pynedist/pyne-ubuntu /bin/sh -c "cd /root/opt/ ; git clone https://github.com/pyne/pyne"
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker commit $commit_id pynedist/pyne-ubuntu
   - sudo docker run pynedist/pyne-ubuntu /bin/sh -c "cd /root/opt/pyne/ ; python setup.py install --user -- -DMOAB_LIBRARY=/root/opt/moab/lib/libMOAB.so -DMOAB_INCLUDE_DIR=/root/opt/moab/include"
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker commit $commit_id pynedist/pyne-ubuntu
script:
   - sudo docker run -e LD_LIBRARY_PATH="/root/.local/lib/" pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/pyne ; /root/.local/bin/nuc_data_make" 
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker commit $commit_id pynedist/pyne-ubuntu
   - sudo docker run -e LD_LIBRARY_PATH="/root/.local/lib/:/root/.local/lib/python2.7/site-packages/PyTAPS-1.4-py2.7-linux-x86_64.egg/:/root/opt/moab/lib" -e PYTHONPATH="/root/.local/lib/python2.7/site-packages/PyTAPS-1.4-py2.7-linux-x86_64.egg/" pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/pyne/tests ; ./travis-run-tests.sh"
   - sudo docker run pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/pyne/tests ; git clone https://github.com/pyne/pyne-amalgamation.git"
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker commit $commit_id pynedist/pyne-ubuntu
   - sudo docker run pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/pyne/ ; python amalgamate.py"
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker commit $commit_id pynedist/pyne-ubuntu
   - sudo docker run pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/pyne/ ; mv pyne.h pyne.cpp tests/pyne-amalgamation"
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker commit $commit_id pynedist/pyne-ubuntu
# need to add amalgamate test
   - sudo docker run -e LIBS="/root/opt/moab/lib:/root/.local/lib" pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/pyne/tests/pyne-amalgamation ; make BASE=$LIBS all"
   - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
   - sudo docker commit $commit_id pynedist/pyne-ubuntu

# command to run tests, e.g. python setup.py test
py.test

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: piovere
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: piovere/stoppingpower
    condition: $TOXENV == py27
